---
title: "Methods"
output: html_document
---

## Methods 

Patient details were submitted electronically by participating sites to the ISARIC database. Relevant background and presenting symptoms were recorded on the day of study recruitment. Daily follow-up was then completed until recovery or death. A final form was completed with details of treatments received and outcomes. All categories that represent fewer than five individuals have been suppressed to avoid the potential for identification of participants.   

Graphs have been used to represent the age distribution of patients by sex and status (dead, recovered & still in hospital), the prevalence of individual symptoms on admission, comorbidities on admission, the length of hospital stay by sex and age group and the distribution of patient statuses by time since admission. In addition, the number of cases recruited by country and site, as well as the case count by status, has been represented.   

All analysis were performed using the R statistical software (R Core Team, 2019). 
