---
title: "Summary"
output: html_document
---


## Summary
The results in this report have been produced using data from the ISARIC COVID-19 database. For information, or to contribute to the collaboration, please contact ncov@isaric.org.  

We thank all of the data contributors for collecting standardised data during these extraordinary times. We plan to issue this report of aggregate data regularly for the duration of the SARS-CoV-2/COVID-19 pandemic.  

Please note the following caveats. This is a dynamic report which captures new variables and information as our understanding of COVID-19 evolves. Please observe the total number of patients of each result to note variables with fewer data points. Information is incomplete for the patients who are still being treated. Furthermore, it is likely that that we received more cases of severely ill individuals than those with relatively less severe illness; outcomes from these data, such as the proportion dying, must therefore not be used to infer outcomes for the entire population of people who might become infected. Some patients may be participants in clinical trials of experimental interventions. Note the variation in patient numbers per country. Additional caveats are provided in the in the ‘Caveats’ section below.  

Up to the date of this report, data have been entered for **`r nrow(summary_input_overall)`** individuals from **`r length(unique(summary_input_overall$siteid_final))`** sites across **`r length(unique(summary_input_overall$slider_country))`** countries.  

The analysis detailed in this report only includes individuals: 

  1. for whom data collection commenced on or before 3 January 2021. (We have applied a 14-day rule to focus analysis on individuals who are more likely to have a recorded outcome. By excluding patients enrolled during the last 14 days, we aim to reduce the number of incomplete data records and thus improve the generalisability of the results and the accuracy of the outcomes;
  
**AND**

  2. who have laboratory-confirmed SARS-COV-2 infection.
  
The cohort satisfying the above criteria has **`r nrow(summary_input)`** cases.
The below flow chart gives an overview of the cohort and outcomes as of 17 January 2021.

## Demographics and presenting features
Of these `r nrow(summary_input)` cases, `r nrow(summary_input %>% filter(slider_sex=='Male'))` are males and `r nrow(summary_input %>% filter(slider_sex=='Female'))` are females – sex is unreported for `r nrow(summary_input %>% filter(is.na(slider_sex)|slider_sex==""))` cases. The minimum and maximum observed ages were `r min(summary_input$age, na.rm=T)` and `r max(summary_input$age, na.rm=T)` years respectively. The median age is `r median(summary_input$age, na.rm=T)` years.  

The observed mean number of days from (first) symptom onset to hospital admission was `r round(mean((summary_input%>%filter(t_son_ad>=0))$t_son_ad, na.rm=T),1)`, with a standard deviation (SD) of `r round(sd((summary_input%>%filter(t_son_ad>=0))$t_son_ad, na.rm=T),1)` days and a median of `r median((summary_input%>%filter(t_son_ad>=0))$t_son_ad, na.rm=T)` days. 

The observed mean duration for the number of days from hospital admission to outcome (death or discharge) was `r round(mean((summary_input%>%filter(slider_outcome=="Death"|slider_outcome=="Discharge"))$dur_ho, na.rm=T),1)`, with SD `r round(sd((summary_input%>%filter(slider_outcome=="Death"|slider_outcome=="Discharge"))$dur_ho, na.rm=T),1)` days and a median of `r median((summary_input%>%filter(slider_outcome=="Death"|slider_outcome=="Discharge"))$dur_ho, na.rm=T)` days. These estimates are based on all cases which have complete records on length of hospital stay (N = `r nrow(summary_input %>%filter((slider_outcome=="Death"|slider_outcome=="Discharge")&! is.na(dur_ho)))`).  

The observed symptoms on admission partly represent case definitions and policies for hospital admission, which may change as time passes. The five most common symptoms at admission were `r glue_collapse(symptom.prevalence.input %>% group_by(nice.symptom) %>% summarise(F=sum(times.present)) %>% ungroup() %>% arrange(desc(F)) %>% slice(1:5) %>% pull(nice.symptom) %>% str_to_lower(), sep = ', ', last=', and ')`. Frequencies of symptom prevalence vary with age. `r paste0(nrow(summary_input %>% filter(vs_oxysat<94)),'/',nrow(summary_input %>% filter(is.na(vs_oxysat)==F)))` (`r round(nrow(summary_input %>% filter(vs_oxysat<94))/nrow(summary_input %>% filter(is.na(vs_oxysat)==F))*100,1)`%) patients presented with oxygen saturations <94%.  

## Outcomes
Outcomes have been recorded for `r nrow(summary_input%>%filter((slider_outcome=="Death"|slider_outcome=="Discharge")))` patients (`r round(nrow(summary_input%>%filter(slider_outcome=="Death"|slider_outcome=="Discharge"))/nrow(summary_input)*100,1)`%), consisting of `r nrow(summary_input%>%filter((slider_outcome=="Discharge")))` recoveries and `r nrow(summary_input%>%filter((slider_outcome=="Death")))` deaths. Outcome records are unavailable for `r nrow(summary_input%>%filter((slider_outcome=="LTFU")))` patients.  

**ICU/HDU**: A total of `r length(which(summary_input$slider_icu_ever==TRUE))` (`r round(length(which(summary_input$slider_icu_ever==TRUE))/nrow(summary_input)*100,0)`%) patients were admitted at some point of their illness into an intensive care unit (ICU) or high dependency unit (HDU), `r round(nrow(summary_input%>% filter(t_ad_icu==0))/nrow(summary_input%>% filter(!is.na(t_ad_icu)))*100,1) `% on the day of admission. Of these, `r nrow(summary_input %>% filter(slider_icu_ever==TRUE & slider_outcome=='Death'))` died, and `r nrow(summary_input %>% filter(slider_icu_ever==TRUE & slider_outcome=='Discharge'))` have recovered and been discharged. Outcome records are unavailable for `r nrow(summary_input %>% filter(slider_icu_ever==TRUE & slider_outcome=='LTFU'))` cases.


Approximately `r round(nrow(summary_input %>% filter(t_ad_icu<1))/sum(is.na(summary_input$t_ad_icu)==F)*100,0)`% of patients with complete records on ICU admission dates were admitted to ICU within the first day of hospital admission. The distribution of the number of days from admission to ICU admission is shown in Figure 11. The duration of stay in ICU/HDU had a mean of `r round(mean(summary_input$dur_icu, na.rm=T),1)` days and a median of `r median(summary_input$dur_icu, na.rm=T)` (SD: `r round(sd(summary_input$dur_icu, na.rm=T),1)` days) – estimated on only those cases with complete records for ICU/HDU duration or ICU/HDU start/end dates (N = `r sum(is.na(summary_input$dur_icu)==F)`). 

## Treatment
Antibiotics were received by `r paste0(length(which(summary_input$treat_antibiotic_agents==T)),'/',sum(is.na(summary_input$treat_antibiotic_agents)==F))` (`r round(length(which(summary_input$treat_antibiotic_agents==T))/sum(is.na(summary_input$treat_antibiotic_agents)==F)*100,1)`%) patients, and `r paste0(length(which(summary_input$treat_antiviral_agents==T)),'/',sum(is.na(summary_input$treat_antiviral_agents)==F))` (`r round(length(which(summary_input$treat_antiviral_agents==T))/sum(is.na(summary_input$treat_antiviral_agents)==F)*100,1)`%) received antivirals. These treatment categories are not mutually exclusive since some patients received multiple treatments. (The denominators differ due to data completeness). `r paste0(length(which(summary_input$oxygen_therapy==T)),'/',sum(is.na(summary_input$oxygen_therapy)==F))` (`r round(length(which(summary_input$oxygen_therapy==T))/sum(is.na(summary_input$oxygen_therapy)==F)*100,1)`%) patients received some degree of oxygen supplementation: of these, `r paste0(length(which(summary_input$treat_non_invasive_ventilation==T)),'/',sum(is.na(summary_input$treat_non_invasive_ventilation)==F))` (`r round(length(which(summary_input$treat_non_invasive_ventilation==T))/sum(is.na(summary_input$treat_non_invasive_ventilation)==F)*100,1)`%) received NIV and `r paste0(length(which(summary_input$treat_invasive_ventilation==T)),'/',sum(is.na(summary_input$treat_invasive_ventilation)==F))` (`r round(length(which(summary_input$treat_invasive_ventilation==T))/sum(is.na(summary_input$treat_invasive_ventilation)==F)*100,1)`%) IMV.  

Of the patients admitted into ICU/HDU, `r paste0(length(which(summary_input$icu_treat_antibiotic_agents==T)),'/',sum(is.na(summary_input$icu_treat_antibiotic_agents)==F ))` (`r round(length(which(summary_input$icu_treat_antibiotic_agents==T))/sum(is.na(summary_input$icu_treat_antibiotic_agents)==F)*100,1)`%) received antibiotics and `r paste0(length(which(summary_input$icu_treat_antiviral_agents==T)),'/',sum(is.na(summary_input$icu_treat_antiviral_agents)==F))` (`r round(length(which(summary_input$icu_treat_antiviral_agents==T))/sum(is.na(summary_input$icu_treat_antiviral_agents)==F)*100,1)`%) antivirals. `r paste0(length(which(summary_input$icu_oxygen_therapy==T)),'/',sum(is.na(summary_input$icu_oxygen_therapy)==F))` (`r round(length(which(summary_input$icu_oxygen_therapy==T))/sum(is.na(summary_input$icu_oxygen_therapy)==F)*100,1)`%) received some degree of oxygen supplementation, of which, `r paste0(length(which(summary_input$icu_treat_non_invasive_ventilation==T)),'/',sum(is.na(summary_input$icu_treat_non_invasive_ventilation)==F))` (`r round(length(which(summary_input$icu_treat_non_invasive_ventilation==T))/sum(is.na(summary_input$icu_treat_non_invasive_ventilation)==F)*100,1)`%) received NIV and `r paste0(length(which(summary_input$icu_treat_invasive_ventilation==T)),'/',sum(is.na(summary_input$icu_treat_invasive_ventilation)==F))` (`r round(length(which(summary_input$icu_treat_invasive_ventilation==T))/sum(is.na(summary_input$icu_treat_invasive_ventilation)==F)*100,1)`%) IMV.  

A total of `r length(which(summary_input$treat_non_invasive_ventilation==T))` patients received non-invasive mechanical ventilation (NIV). The mean and median durations from admission to receiving NIV were `r round(mean(summary_input$t_ad_niv, na.rm=T),1)` days and `r median(summary_input$t_ad_niv, na.rm=T)` days respectively (SD: `r round(sd(summary_input$t_ad_niv, na.rm=T),1)` days) – estimated from records on cases with complete records on dates of hospital admission and NIV onset (N = `r sum(is.na(summary_input$t_ad_niv)==F)`). The mean and median durations for NIV were `r round(mean(summary_input$dur_niv, na.rm=T),1)` days and `r median(summary_input$dur_niv, na.rm=T)` days respectively (SD: `r round(sd(summary_input$dur_niv, na.rm=T),1)` days) – estimated based on only those cases which have complete NIV duration records (N = `r sum(is.na(summary_input$dur_niv)==F)`).  

A total of `r length(which(summary_input$treat_invasive_ventilation==T))` patients received invasive mechanical ventilation (IMV). The mean and median durations from admission to receiving IMV were `r round(mean(summary_input$t_ad_imv, na.rm=T),1)` days and `r median(summary_input$t_ad_imv, na.rm=T)` days respectively (SD: `r round(sd(summary_input$t_ad_imv, na.rm=T),1)` days) – estimated from records on cases with complete records on dates of hospital admission and IMV onset (N = `r sum(is.na(summary_input$t_ad_imv)==F)`). The mean, median and SD for the duration of IMV – estimated based on all `r sum(is.na(summary_input$dur_imv)==F)` cases with complete records on IMV stays – were `r round(mean(summary_input$dur_imv, na.rm=T),1)` days, `r median(summary_input$dur_imv, na.rm=T)` days and `r round(sd(summary_input$dur_imv, na.rm=T),1)` days respectively.  

Corticosteroids were administered to `r paste0(length(which(summary_input$treat_corticosteroids==T)),'/',sum(is.na(summary_input$treat_corticosteroids)==F))` (`r round(length(which(summary_input$treat_corticosteroids==T))/sum(is.na(summary_input$treat_corticosteroids)==F)*100,1)`%) patients. This includes `r paste0(nrow(summary_input %>% filter(treat_corticosteroids==T & treat_invasive_ventilation==T)),'/',nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & treat_invasive_ventilation==T)))` (`r round(nrow(summary_input %>% filter(treat_corticosteroids==T & treat_invasive_ventilation==T))/nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & treat_invasive_ventilation==T))*100,1)`%) of those who received IMV, `r paste0(nrow(summary_input %>% filter(treat_corticosteroids==T & treat_invasive_ventilation==F & oxygen_therapy==T)),'/',nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & treat_invasive_ventilation==F & oxygen_therapy==T)))` (`r round(nrow(summary_input %>% filter(treat_corticosteroids==T & treat_invasive_ventilation==F & oxygen_therapy==T))/nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & treat_invasive_ventilation==F & oxygen_therapy==T))*100,1)`%) of those who had oxygen therapy but not IMV, and `r paste0(nrow(summary_input %>% filter(treat_corticosteroids==T & oxygen_therapy==F)),'/',nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & oxygen_therapy==F)))` (`r round(nrow(summary_input %>% filter(treat_corticosteroids==T & oxygen_therapy==F))/nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & oxygen_therapy==F))*100,1)`%) of those who had no oxygen therapy. On 16 June, results for dexamethasone were released for the RECOVERY randomized controlled trial (RECOVERY, 2020; RECOVERY Collaborative Group, 2020). This trial found that dexamethasone reduced deaths for patients receiving IMV and oxygen therapy, but not among patients not receiving respiratory support. Of patients admitted since 16 June, corticosteroids were received by `r paste0(nrow(summary_input %>% filter(treat_corticosteroids==T & treat_invasive_ventilation==T & date_admit>'2020-06-16')),'/',nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & treat_invasive_ventilation==T & date_admit>'2020-06-16')))` (`r round(nrow(summary_input %>% filter(treat_corticosteroids==T & treat_invasive_ventilation==T & date_admit>'2020-06-16'))/nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & treat_invasive_ventilation==T & date_admit>'2020-06-16'))*100,1)`%) of those who received IMV, `r paste0(nrow(summary_input %>% filter(treat_corticosteroids==T & treat_invasive_ventilation==F & oxygen_therapy==T & date_admit>'2020-06-16')),'/',nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & treat_invasive_ventilation==F & oxygen_therapy==T & date_admit>'2020-06-16')))` (`r round(nrow(summary_input %>% filter(treat_corticosteroids==T & treat_invasive_ventilation==F & oxygen_therapy==T & date_admit>'2020-06-16'))/nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & treat_invasive_ventilation==F & oxygen_therapy==T & date_admit>'2020-06-16'))*100,1)`%) of those who had oxygen therapy but not IMV, and `r paste0(nrow(summary_input %>% filter(treat_corticosteroids==T & oxygen_therapy==F & date_admit>'2020-06-16')),'/',nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & oxygen_therapy==F & date_admit>'2020-06-16')))` (`r round(nrow(summary_input %>% filter(treat_corticosteroids==T & oxygen_therapy==F & date_admit>'2020-06-16'))/nrow(summary_input %>% filter(is.na(treat_corticosteroids)==F & oxygen_therapy==F & date_admit>'2020-06-16'))*100,1)`%) of those who had no oxygen therapy.
