---
title: "welcome page"
output: html_document
---

### Caveats

1) This is a dynamic report which captures new variables and information as our understanding of COVID-19 evolves. Please observe the total number of patients of each result to note variables with fewer data points.

2) It is likely that that we received more cases of severely ill individuals than those with relatively less severe illness; outcomes from these data, such as the proportion dying, must therefore not be used to infer outcomes for the entire population of people who might become infected. 

3) Patient data are collected and uploaded from start of admission, however a complete patient data set is not available until the episode of care is complete. This causes a predictable lag in available data influenced by the duration of admission which is greatest for the sickest patients, and accentuated during the up-phase of the outbreak.

4) These reports provide regular outputs from the ISARIC COVID-19 database. We urge caution in interpreting unexpected results. We have noted some unexpected results in the report, and are working with sites that submitted data to gain a greater understanding of these.

5) Please pay attention to the denominators in the the frequency plots as they are ordered by proportion rather than frequency.

6) Please note that the data is split on death/discharge/LTFU mutually exclusive but not exhaustive due to missing data.

7) Some patients may be participants in clinical trials of experimental interventions. 
